# Generated by Django 4.2.5 on 2023-10-26 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kilograms",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "calories",
                    models.FloatField(
                        blank=True, help_text="Daily calorie requirements", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_picture/"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Body Mass Index",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True, help_text="Blood Pressure", max_length=15, null=True
                    ),
                ),
                (
                    "blood_glucose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Blood Glucose Level",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "cholesterol",
                    models.JSONField(
                        blank=True, help_text="Cholesterol Levels (JSON)", null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
